spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3336/test
    username: root
    password: admin123
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 실행 되는 SQL 문을 보여 줄지 설정\
#    properties:
#      hibernate.format_sql: true # 형식화된 sql 문을 보여준다. Beautifier 기능이라고 생각하면 된다
#      hibernate.enable_lazy_load_no_trans: true #Lazy Load 를 적용하기 위한 설정
  thymeleaf:
    cache: false
    mode: HTML 
server:
  port: 19010
  compression:
    mime-types: text/html,text/css,application/json
mybatis:
  mapper-locations: /mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true